api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('items/', views.getAllItems, name='get-all-items'),
    path('browse/', views.browse_transactions, name='browse-all-items'),
    path('new/', views.newItem, name='create-new-item'),
    path('items/<int:pk>/', views.getItem, name='get-item'),
    path('items/<int:pk>/buy/', views.buyItem, name='buy-item'),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from dj_rest_auth import views as JWTViews

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', auth_views.LogoutView.as_view(next_page='core:login'), name='logout'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    #path('login/', JWTViews.LoginView.as_view(next_page='core:index'), name='login'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name='dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

items/urls.py
from django.urls import path

from . import views

app_name = 'items'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('', views.browse, name='browse'),
    path('<int:pk>/', views.detail, name='detail'),
]

market/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf import settings
# from django.conf.urls.static import static

from core.views import index, contact

urlpatterns = [
    path("", include('core.urls')),
    path('items/', include('items.urls')),
    path("admin/", admin.site.urls),
    path('dashboard', include('dashboard.urls')),
    path('api/v1/', include('api.urls')),
] 

core/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.
class Role(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, related_name='roles', on_delete=models.CASCADE)

    def __str__(self):
        return "Name: " + self.user.username + ", Role: " + self.role.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.contrib.auth.models import User
from .models import Role, UserProfile


class SignupForm(UserCreationForm):
    role = forms.ModelChoiceField(queryset=Role.objects.all(), required=True, label='Role')

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'role')

    username = forms.CharField(widget=forms.TextInput())
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    def save(self, commit=True):
        user = super().save(commit=commit)
        role = self.cleaned_data['role']
        if commit:
            UserProfile.objects.create(user=user, role=role)
        return user

class LoginForm(AuthenticationForm):
        
    username = forms.CharField(widget=forms.TextInput())

    password= forms.CharField(widget=forms.PasswordInput())

core/views.py
from django.shortcuts import render, redirect
#from django.contrib.auth import logout

from items.models import Product, Transaction

from .forms import SignupForm
from .models import UserProfile, Role

from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status

import logging

# !!!ADD LOGGERS
# Appropriate comments, README
#Serializer?

# Create your views here.

# Configure basic logging (e.g., to console)
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Get a logger instance
logger = logging.getLogger(__name__)

def isFarmer(request):
    if request.user.is_authenticated:
        try:
            farmer_role = Role.objects.get(name = 'Farmer')
            return UserProfile.objects.filter(user=request.user, role=farmer_role)
        except Role.DoesNotExist:
            logger.info("Not a farmer")
            return False
    else:
        logger.error("Not logged in" + "User: " + str(request.user))
        return False
    
def isCustomer(request):
    if request.user.is_authenticated:
        try:
            customer_role = Role.objects.get(name = 'Customer')
            return UserProfile.objects.filter(user=request.user, role=customer_role)
        except Role.DoesNotExist:
            logger.info("Not a customer")
            return False
    else:
        logger.error("Not logged in" + "User: " + str(request.user))
        return False


def index(request):
    transactions = Transaction.objects.filter(is_sold=False).order_by('-created_at')[0:6]
    products = Product.objects.all()
    return render(request, 'core/index.html', {
        'transactions': transactions,
        'products': products,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')

    form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })
'''
def logout_view(request):
    logout(request)

    return redirect(request, '/logout/')'''

templates/core/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script src="https://cdn.tailwindcss.com"></script>

        <title> {% block title %}{% endblock %} | Market Place </title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">Marketplace</a>

            <div class="space-x-6">

                {% if request.user.is_authenticated %}

                <a href="{% url 'items:browse' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

                <a href="{% url 'items:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>

                <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700"> My items </a>

                <form action="{% url 'core:logout' %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Logout</button>
                </form>

                {% else %}

                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700"> Sign Up </a>

                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700"> Login </a>

                <a href="{% url 'admin:login' %}" class="px-6 py-3 text-lg font-semibold bg-cyan-500 text-white rounded-xl hover:bg-cyan-700"> Admin Login </a>

                {% endif %}
            </div>

        </nav>
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500"> Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet </p>
            </div>

            <div class="w-1/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of Use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
<h1> The contact Page </h1>
{% endblock %}

templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Newest Items</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in transactions %}
        <div>
            <a href="{% url 'items:detail' item.id %}">
                <div class = "p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{ item.name }}</h2>
                    <p class="text-gray-500">Price: {{ item.price }}Rs</p>
                    <p class="text-gray-500">Quantity: {{ item.quantity }}Kg</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <div class="grid grid-cols-3 gap-3">
        {% for product in products %}
        <div>
            <a href="#">
                <div class = "p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{ item.name }}</h2>
                    <p class="text-gray-500">{{product.name}}: {{ product.transactions.count }} items</p>
                </div>
            </a>
        </div>
        {% endfor %}

{% endblock %}

templates/core/login.html
{% extends 'core/base.html' %}
{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="w1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log In</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>{{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>{{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}

            </div>
        {% endif %}


        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

templates/core/signup.html
{% extends 'core/base.html' %}
{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="w1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>{{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>{{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat Password</label><br>{{ form.password2 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Select Role</label><br>{{ form.role }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}

            </div>
        {% endif %}


        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}